version: '3.4'

services:
  inventory:
    image: inventory
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3009:3009
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
