apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: inventory
build:
  artifacts:
    - image: dxcore98/inventory
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    sha256: {}
manifests:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/service.yaml
