apiVersion: apps/v1
kind: Deployment
metadata:
  name: digpos
spec:
  selector:
    matchLabels:
      app: digpos
  replicas: 2
  template:
    metadata:
      labels:
        app: digpos
    spec:
      containers:
        - name: inventory
          image: dxcore98/inventory:latest
          env:
          - name: DB_URI
            value: mongodb+srv://dickyd9:R0bdkBMLNwQLtapP@dxdatabase.mxy2ki9.mongodb.net/
          - name: SECRET_JWT
            value: khasdnb,vlaj2r8o234/df
          - name: IS_PUBLIC_KEY
            value: Guaz2qeKsM06x1ZRI5OaTg==
          - name: IS_SECRET_KEY
            value: zoz175xeYOtcpMrpPepTCQ==
          - name: JWT_ACCESS_TOKEN_EXPIRATION
            value: "0"
          - name: JWT_REFRESH_TOKEN_EXPIRATION
            value: "2592000"
          - name: USE_JSON_LOG
            value: Sjahd4m2npi435==
          - name: DEBUG
            value: Asdamf435r34j==

          ports:
            - containerPort: 3009
